### ISSUE TITLE
Can you push the release 1.0.1 to Maven/Gradle Repo?

### ISSUE THREAD

**Issue by harinair** [smanikandan14/ThinDownloadManager#35]
Adding the source or jar to my project is yucky. Can you fix the 1.0.1 dependency issue?

**Comment by smanikandan14** [comment]
It is fixed. Use jcenter() and download the library as gradle dependency.

**Comment by harinair** [comment]
Still not in jcenter:
https://repo.jfrog.org/artifactory/libs-release-bintray/com/mani/thindownloadmanager/
https://jcenter.bintray.com/com/mani/thindownloadmanager

I can see only 1.0.0.

**Comment by harinair** [comment]
Saw the change in artifact name. Thx.
